### ISSUE TITLE
コマンド実行に関する部分でメモリリークが発生する

### ISSUE THREAD

**Issue by JUNNETWORKS** [torus/42-minishell#138]
前まで無かったのに...

原因調べて直します.

**Comment by JUNNETWORKS** [comment]
```
[KO] case: env | grep -v -E '^_=' | sort
---------------------------------
# minishell: stdout
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LS_COLORS=
OLDPWD=/home/jun/Desktop/work_space/42tokyo/42_minishell_tester/test
PATH=/.dotnet:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/jun/Desktop/work_space/42tokyo/42_minishell_tester/test
SHLVL=3
# bash     : stdout
LESSCLOSE=/usr/bin/lesspipe %s %s
LESSOPEN=| /usr/bin/lesspipe %s
LS_COLORS=
OLDPWD=/home/jun/Desktop/work_space/42tokyo/42_minishell_tester/test
PATH=/.dotnet:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/home/jun/Desktop/work_space/42tokyo/42_minishell_tester/test
SHLVL=2
# minishell: stderr

=================================================================
==299300==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 72 byte(s) in 1 object(s) allocated from:
    #0 0x7fe37d052bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x5610b3126b84 in ft_calloc (/home/jun/Desktop/work_space/42tokyo/minishell/minishell+0x1bb84)
    #2 0x5610b3119949 in vars2environ /home/jun/Desktop/work_space/42tokyo/minishell/t_var2.c:69
    #3 0x5610b3119e6e in builtin_env /home/jun/Desktop/work_space/42tokyo/minishell/builtin_env.c:14
    #4 0x5610b3110087 in cmd_exec_command /home/jun/Desktop/work_space/42tokyo/minishell/cmd_exec_command.c:52
    #5 0x5610b31105ed in cmd_exec_commands /home/jun/Desktop/work_space/42tokyo/minishell/cmd_exec_commands.c:61
    #6 0x5610b311ce81 in invoke_sequential_commands /home/jun/Desktop/work_space/42tokyo/minishell/minishell.c:44
    #7 0x5610b311d1b7 in do_command /home/jun/Desktop/work_space/42tokyo/minishell/minishell.c:68
    #8 0x5610b311d2f1 in main /home/jun/Desktop/work_space/42tokyo/minishell/minishell.c:81
    #9 0x7fe37cd4a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 354 byte(s) in 8 object(s) allocated from:
    #0 0x7fe37d052bc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x5610b3126ce5 in ft_strjoin (/home/jun/Desktop/work_space/42tokyo/minishell/minishell+0x1bce5)
    #2 0x5610b3111a57 in generate_kvstr /home/jun/Desktop/work_space/42tokyo/minishell/env_setter.c:15
    #3 0x5610b3119a2f in vars2environ /home/jun/Desktop/work_space/42tokyo/minishell/t_var2.c:75
    #4 0x5610b3119e6e in builtin_env /home/jun/Desktop/work_space/42tokyo/minishell/builtin_env.c:14
    #5 0x5610b3110087 in cmd_exec_command /home/jun/Desktop/work_space/42tokyo/minishell/cmd_exec_command.c:52
    #6 0x5610b31105ed in cmd_exec_commands /home/jun/Desktop/work_space/42tokyo/minishell/cmd_exec_commands.c:61
    #7 0x5610b311ce81 in invoke_sequential_commands /home/jun/Desktop/work_space/42tokyo/minishell/minishell.c:44
    #8 0x5610b311d1b7 in do_command /home/jun/Desktop/work_space/42tokyo/minishell/minishell.c:68
    #9 0x5610b311d2f1 in main /home/jun/Desktop/work_space/42tokyo/minishell/minishell.c:81
    #10 0x7fe37cd4a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: 426 byte(s) leaked in 9 allocation(s).
# bash     : stderr
# minishell: exit status = 0
# bash     : exit status = 0
```

**Comment by JUNNETWORKS** [comment]
sanitizerのオプションがつけっぱなしでvalgrindとぶつかってただけでした.
